set(_CATKIN_CURRENT_PACKAGE "Team_08")
set(Team_08_VERSION "0.0.0")
set(Team_08_MAINTAINER "joe <joedgallagher@wpi.edu>")
set(Team_08_PACKAGE_FORMAT "2")
set(Team_08_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(Team_08_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(Team_08_BUILDTOOL_DEPENDS "catkin")
set(Team_08_BUILDTOOL_EXPORT_DEPENDS )
set(Team_08_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(Team_08_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(Team_08_TEST_DEPENDS )
set(Team_08_DOC_DEPENDS )
set(Team_08_DEPRECATED "")